apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: YOUR_DOCKERHUB_USERNAME/shop-app:latest
        command: ["celery", "-A", "core", "worker", "-l", "info"]
        envFrom:
        - secretRef:
            name: shop-secrets
